config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users do
    resources :foods, except: :update
    resources :recipes, except: :index do
      member do
        get :toggle_public
      end
      resources :recipe_foods, only: [:create,:new,:index, :destroy]
    end
    
  end
  # Defines the root path route ("/")
  get '/recipes', to: 'recipes#index'
  # get '/general_shopping_list', to: 'user#general_shopping_list' 
 get '/public_recipes', to: 'recipes#public_recipes'
  root 'recipes#index' 
  get '/general_shopping_list', to: 'foods#shopping_list'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    if user.is? :admin
      can :manage,:all
    else
      can :read, Recipe,public: true
      can :manage,Recipe,user:user
      can :manage,RecipeFood,user:user
    end
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :recipes, class_name: 'Recipe', foreign_key: 'recipe_id', through: :recipe_foods
  has_many :recipe_foods, dependent: :delete_all
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_many :foods, foreign_key: 'food_id', through: :recipe_foods
  has_many :recipe_foods, dependent: :delete_all
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food, class_name: 'Food', foreign_key: 'food_id'
  belongs_to :recipe, class_name: 'Recipe', foreign_key: 'recipe_id'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :foods
  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  private

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :surname, :email, :password, :current_password)
    end
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.all
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    @food.user_id = current_user.id

    respond_to do |format|
      format.html do
        if @food.save
          flash[:success] = 'Food successfully saved'
          redirect_to user_foods_path(current_user)
        else
          flash[:error] = 'Something went wrong'
          render new
        end
      end
    end
  end

  def destroy
    @food = Food.find(params[:id])
    respond_to do |format|
      format.html do
        if @food.destroy
          flash[:success] = 'Food successfully deleted'
          redirect_to user_foods_path(current_user)
        else
          flash[:error] = 'Something went wrong'
          render index
        end
      end
    end
  end

  def shopping_list
    @recipes = Recipe.where(user_id: current_user.id)
    @ingredients = RecipeFood.where(recipe_id: @recipes.map(&:id))
    @foods = Food.where(id: @ingredients.map(&:food_id))
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :quantity, :price)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def index
    @recipe_foods = RecipeFood.all
  end

  def new
    @recipe_food = RecipeFood.new
    @foods = Food.all
  end

  def create
    @recipe_food = RecipeFood.new(recipe_food_params)
    @foods = Food.all
    @recipe_food.recipe_id = params[:recipe_id]
    respond_to do |format|
      format.html do
        if @recipe_food.save
          flash[:success] = 'Ingredient successfully saved'
          redirect_to user_recipe_path(id: params[:recipe_id])
        else
          flash[:error] = 'Something went wrong'
          render :new
        end
      end
    end
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    respond_to do |format|
      format.html do
        if @recipe_food.destroy
          flash[:success] = 'ingredient successfully deleted'
          redirect_to user_recipe_path(current_user)
        else
          flash[:error] = 'Something went wrong'
          render :index
        end
      end
    end
  end

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.where(user_id: current_user.id)
  end

  def new
    @recipe = Recipe.new
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipe_foods = RecipeFood.where(recipe_id: @recipe.id)
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.preparation_time =
      "PT#{params[:recipe][:prep_hours]}H#{params[:recipe][:prep_minutes]}M#{params[:recipe][:prep_seconds]}S"
    @recipe.cooking_time =
      "PT#{params[:recipe][:cooking_hours]}H#{params[:recipe][:cooking_minutes]}M#{params[:recipe][:cooking_seconds]}S"
    @recipe.user_id = current_user.id
    respond_to do |format|
      format.html do
        if @recipe.save
          flash[:success] = 'Object successfully deleted'
          redirect_to recipes_path(current_user)
        else
          flash[:error] = 'Something went wrong'
          render new
        end
      end
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    respond_to do |format|
      format.html do
        if @recipe.destroy
          flash[:success] = 'Recipe successfully deleted'
          redirect_to user_recipes_path(current_user)
        else
          flash[:error] = 'Something went wrong'
          render :index
        end
      end
    end
  end

  def toggle_public
    recipe = Recipe.find(params[:id])
    recipe.public = if recipe.nil?
                      false
                    else
                      !recipe.public
                    end
    recipe.save
    redirect_to user_recipe_path
  end

  def public_recipes
    @public_recipes = Recipe.all.where(public: true).order(created_at: :desc)
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :description, :preparation_time, :cooking_time)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @user = User.all
  end

  # def create
  #     @user = User.new(user_params)
  #     respond_to do |format|
  #         format.html do

  #         end
  #     end
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end

  def general_shopping_list; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/foods/index.html.erb
<section class="py-10 flex flex-col gap-10 bg-yellow-50">
<div class="lg:w-3/6 w-5/6 m-auto">
<%= button_to 'Add new food', new_user_food_path(current_user), method: :get, class:"float-right bg-amber-400 p-3 rounded-3xl hover:bg-amber-500 text-white"%>
</div>


  <div class="lg:w-3/6 w-5/6 m-auto bg-white">
    <table class="w-full border table-auto">
      <thead>
        <tr>
          <th>Food</th>
          <th>Measurement unit</th>
          <th>Unit price</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>

        <% @foods.each do |food|%>
          <tr class="bg-gray-50 text-center">
            <td class="p-2 border-r"><%= food.name %></td>
            <td class="p-2 border-r"><%= food.measurement_unit %></td>
            <td class="p-2 border-r"><%= "$#{food.price}" %></td>
            <td class="p-2 border-r">
              <%= button_to "Delete", user_food_path(id: food.id, user_id: food.user_id), method: :delete, class: "focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-2 focus:ring-red-300 font-medium rounded-lg text-sm px-4 py-2 mr-1 mb-1 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900" %>
            </td>
          </tr>
        <% end %>

      </tbody>
    </table>
  </div>

</section>

app/views/foods/new.html.erb
<div class="h-5/6 flex flex-col justify-center items-center">
    <%= render partial:"shared/new_food", locals:{food: @food, path: user_foods_path}%>
</div>

app/views/foods/shopping_list.html.erb
<section class="py-10 flex flex-col gap-10 bg-yellow-50">
  <h2 class="text-5xl font-normal leading-normal lg:w-3/6 w-5/6 m-auto">Shopping List</h2>

  <div class="lg:w-3/6 w-5/6 m-auto flex justify-between">
    <h3>Amount of food items to buy: <%= @ingredients.count %> </h3>
    <h3>Total value of food needed: 
            <% sum = 0 %>
            <% @ingredients.each { |food_recipe| sum += Food.find(food_recipe.food_id).price * food_recipe.quantity} %>
             <%= "$#{sum}" %>
        </h3>
  </div>

  <div class="lg:w-3/6 w-5/6 m-auto bg-white">
    <table class="w-full border table-auto">
      <thead>
        <tr>
          <th>Food</th>
          <th>Quantity</th>
          <th>Price</th>
        </tr>
      </thead>
      <tbody>

        <% @ingredients.each do |food|%>
          <tr class="bg-gray-50 text-center">
            <td class="p-2 border-r"><%= food.food.name %></td>
            <td class="p-2 border-r"><%=food.quantity %> <%= food.food.measurement_unit %></td>
            <td class="p-2 border-r"><%= "$#{food.quantity * food.food.price}" %></td>
          </tr>
        <% end %>

      </tbody>
    </table>
  </div>


</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="h-screen">
  
    
    <main class="w-full h-full">
    <% if user_signed_in? %>
      <%= render partial:"shared/navbar"%>
    <% end %>
      <%= yield %>
      
    </main>
  </body>
</html>

app/views/recipe_foods/new.html.erb
<div class="h-5/6 flex flex-col justify-center items-center">
 <%= form_with model: @recipe_food, url: user_recipe_recipe_foods_path, method: :post, local: true, class:" border-2 w-3/5 flex flex-col items-center px-20 py-6"  do |f|%>
    <div class="flex flex-col w-full mb-2">
            <%= f.label :food_id, "Name of food" %>
            <%= f.select :food_id, @foods.collect{ |u| [u.name, u.id] } %>
    </div>
    <div class="flex flex-col w-full mb-2">
        <%= f.label :quantity, "Quantity" %>
        <%= f.number_field :quantity %>
    </div>

    <%= f.submit "Create ingredient", class: "text-white bg-gradient-to-r from-blue-500 via-blue-600 cursor-pointer to-blue-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 
    font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2" %>
 <% end %>
</div>

app/views/recipes/index.html.erb
<section class="py-10 flex flex-col gap-10 bg-yellow-50">
<div class="lg:w-3/6 w-5/6 m-auto">
<%= button_to 'create new recipe', new_user_recipe_path(current_user), method: :get, class:"float-right bg-amber-400 p-3 rounded-3xl hover:bg-amber-500 text-white"%>
</div>
<% @recipes.each do |recipe|%>

    <article class="flex  md:gap-20 gap-5 justify-between bg-yellow-200 p-7 rounded-lg lg:w-3/6 w-5/6 m-auto" >
        <div class="flex flex-col ">
        <%= link_to user_recipe_path(id: recipe.id, user_id: current_user.id), class:"mb-4" do%>
        <h2 class="text-2xl font-medium text-indigo-900"><%= recipe.name %></h2>
        <% end %>
        <%= button_to "Remove", user_recipe_path(id: recipe.id,user_id: current_user.id), method: :delete, class:"bg-red-500 text-white py-1 px-4 rounded-full tracking-wider" %>
        </div>
        <p><%= recipe.description %></p>
    </article>
    
<%end%>
</section>

app/views/recipes/new.html.erb
<div class="h-5/6 flex flex-col justify-center items-center">
<%= form_with model: @recipe, url: user_recipes_path, method: :post, local: true, class:" border-2 w-3/5 flex flex-col items-center px-20 py-6"  do |f|%>
        <div class="flex flex-col w-full">
            <%= f.label :name,"Name of recipe" %>
            <%= f.text_field :name%>
        </div>
        <div class="flex flex-col w-full">
            <%= f.label :description,"Description" %>
            <%= f.text_area :description%>
        </div>
        <div >
            <h2 class="text-xl ">Preparation time</h2>
            <div class="inline-flex w-full gap-10 flex-wrap">
            <div class="flex flex-col w-1/4">
            <%= f.label :prep_hours, 'Hours: '%>
            <%= f.number_field :prep_hours,max: 24,min: 0, class:"w-full" %>
            </div>
            <div class="flex flex-col w-1/4">
            <%= f.label :prep_minutes, 'Minutes: '%>
            <%= f.number_field :prep_minutes, class:"w-full" %>
            </div>
            <div class="flex flex-col w-1/4">
            <%= f.label :prep_seconds, 'Seconds: '%>
            <%= f.number_field :prep_seconds,class:"w-full" %>
            </div>

            <%= f.hidden_field :Preparation_time, value: "" %>
        <div>
        <div >
            <h2 class="text-xl ">Cooking time</h2>
            <div class="inline-flex w-full gap-10 flex-wrap">
            <div class="flex flex-col w-1/4">
            <%= f.label :cooking_hours, 'Hours: '%>
            <%= f.number_field :cooking_hours,max: 24,min: 0, class:"w-full" %>
            </div>
            <div class="flex flex-col w-1/4">
            <%= f.label :cooking_minutes, 'Minutes: '%>
            <%= f.number_field :cooking_minutes, class:"w-full" %>
            </div>
            <div class="flex flex-col w-1/4">
            <%= f.label :cooking_seconds, 'Seconds: '%>
            <%= f.number_field :cooking_seconds,class:"w-full" %>
            </div>

            <%= f.hidden_field :cooking_time, value: "" %>
        <div>

        <%= f.submit "Submit"%>

<% end %>
</div>

app/views/recipes/public_recipes.html.erb
<section class="py-10 flex flex-col gap-10 bg-yellow-50">
  <h2 class="text-5xl font-normal leading-normal lg:w-3/6 w-5/6 m-auto">Public recipes</h2>
  <% @public_recipes.each do |recipe| %>
  <%= link_to user_recipe_path(id: recipe.id, user_id: current_user.id) do %>
    <% sum = 0 %>
      <article class="flex lg:w-3/6 w-5/6 m-auto md:gap-20 gap-5 justify-between bg-yellow-200 p-7 rounded-lg" >
          <div class="flex flex-col ">
            <h2 class="text-2xl"><%= recipe.name %></h2>
            <h3>By: <%= recipe.user.name %></h3>
          </div>
          <div>
            <p>Total Food Items: <%= recipe.recipe_foods.count %></p>
            <% recipe.recipe_foods.each {|food| sum += food.quantity * food.food.price} %>
            <h3>Total Price: <%= sum %></h3>
          <div>
      </article>
      <%end%>
  <% end %>
</section>

app/views/recipes/show.html.erb
<section class="py-10 px-24 text-gray-800">
<h1 class="font-semibold text-3xl text-center mb-6"><%= @recipe.name%></h1>
<div class="flex justify-between ">
    <div class="flex flex-col gap-10 ">
        <h3 class="text-xl font-medium">Preparation Time: <%= @recipe.preparation_time.in_hours.round(2) %> hours</h3>
        <h3 class="text-xl font-medium">Cooking Time: <%= @recipe.cooking_time.in_hours.round(2) %> hours</h3>
        <p class="text-lg">Steps go here ....</p>
    </div>
    <div>
        <h2 class="font-medium text-2xl mb-3">Public</h2>
        <%= link_to  toggle_public_user_recipe_path do %> 
            <div class="w-20 p-0.5 border-gray-900 h-8 rounded-full 
            flex items-center <%= @recipe.public ? "justify-end bg-green-600" : " justify-start bg-gray-300" %>" >
                <div class="w-2/5 border-gray-900 h-7 rounded-full bg-white">
                </div>
            </div>
        <% end %> 
    </div>
</div>

<div class="flex justify-between lg:w-4/6 w-5/6 m-auto">
<%= button_to 'Generate shopping list', general_shopping_list_path, method: :get, class:"float-right bg-gray-500 p-3 rounded-xl hover:bg-amber-500 text-white"%>
<%= button_to 'Add ingredient', new_user_recipe_recipe_food_path(current_user,@recipe), method: :get, class:"float-right bg-amber-400 p-3 rounded-xl hover:bg-amber-500 text-white"%>
</div>

  <div class="lg:w-4/6 w-5/6 m-auto bg-white mt-10">
    <table class="w-full border table-auto">
      <thead>
        <tr>
          <th>Food</th>
          <th>Quantity</th>
          <th>value</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>

        <% @recipe_foods.each do |r_food|%>
          <tr class="bg-gray-50 text-center">
            <td class="p-2 border-r"><%= r_food.food.name %></td>
            <td class="p-2 border-r"><%= r_food.quantity %></td>
            <td class="p-2 border-r"><%= "$#{if r_food.quantity == nil
            0
            else
             r_food.food.price*r_food.quantity
             end}" %></td>
            <td class="p-2 border-r flex justify-center">
              <%= button_to "Modify", user_recipe_path(id: r_food.recipe_id, user_id: current_user.id), method: :update, class: "focus:outline-none text-white bg-amber-500 hover:bg-amber-700 focus:ring-2 focus:ring-amber-300 font-medium rounded-lg text-sm px-4 py-2 mr-1 mb-1 dark:bg-amber-600 dark:hover:bg-amber-700 dark:focus:ring-amber-900" %>
              <%= button_to "Remove", user_recipe_recipe_food_path(id: r_food.id, user_id: current_user.id,recipe_id: r_food.recipe_id ), method: :delete, class: "focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-2 focus:ring-red-300 font-medium rounded-lg text-sm px-4 py-2 mr-1 mb-1 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900" %>
            </td>
          </tr>
        <% end %>

      </tbody>
    </table>
  </div>

</section>

app/views/shared/_navbar.html.erb
<% unless current_page?(new_user_session_path)||current_page?(new_user_registration_path)%>
<nav class="flex justify-end w-full">
   <div class="flex p-5 justify-between w-2/3 px-20">
   <ul class="flex justify-between w-3/5">
   <li><%= link_to  'Food Ingredents', user_foods_path(current_user)%></li>
   <li><%= link_to  'Recipes', recipes_path(current_user) %></li>
   <li><%= link_to  'Public Recipes', public_recipes_path %></li>
   </ul>
   <ul>
    <li><%= link_to "Log out", destroy_user_session_path, 
    class: 'nav-link', data: { turbo_method: :delete } %>
    </li>
   </ul>
   </div>
</nav>
<% end %>

app/views/shared/_new_food.html.erb
<%= form_with model: food, url: path, method: :post, local: true, class:" border-2 w-3/5 flex flex-col items-center px-20 py-6"  do |f|%>
        <div class="flex flex-col w-full mb-2">
            <%= f.label :name, "Name of food" %>
            <%= f.text_field :name%>
        </div>
        <div class="flex flex-col w-full mb-2">
            <%= f.label :measurement_unit, "Measurement Unit" %>
            <%= f.text_field :measurement_unit%>
        </div>

        <div class="flex flex-col w-full mb-2">
            <%= f.label :quantity, "Quantity" %>
            <%= f.number_field :quantity,min: 0, class:"w-full" %>
        </div>

        <div class="flex flex-col w-full mb-2">
            <%= f.label :price, "Price" %>
            <%= f.number_field :price,min: 0, class:"w-full" %>
        </div>

        <%= f.submit "Submit", class: "text-white bg-gradient-to-r from-blue-500 via-blue-600 cursor-pointer to-blue-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2" %>

<% end %>